name=crst01a_arduino_lib
version=1.0.0
author=CuboRex
maintainer=CuboRex
sentence=A driver for controlling CRST01A with Arduino.
paragraph=A driver for controlling CRST01A with Arduino.
category=Device Control
url=https://github.com/CuboRex-Development/crst01a_arduino_lib
architectures=*
includes=difDriver_ctrl.h
